# Generated by Django 4.2.21 on 2025-06-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_tutorialcard_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comsesdigest",
            name="static_path",
        ),
        migrations.AddField(
            model_name="comsesdigest",
            name="url",
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
